### ISSUE TITLE
Weird ExtractAllEntries error

### ISSUE THREAD

**Issue by hellfirehd** [zerratar/SubSync#13]
```
PS D:\SubSync> dotnet run --project .\src\SubSync\SubSync.csproj \\c3p0\storage\media -exit
...
Synchronizing Will & Grace - S07E16 - Dance Cards and Greeting Cards DVD.avi
[DBG] get-async: 'Will & Grace - S07E16 - Dance Cards and Greeting Cards DVD.avi'
[DBG] Searching for 'Will & Grace - S07E16 - Dance Cards and Greeting Cards DVD.avi'...
[DBG] Searching with query 'Will & Grace - S07E16 - Dance Cards and Greeting Cards DVD.avi'...
Synchronization of Will & Grace - S07E16 - Dance Cards and Greeting Cards DVD.avi failed with: Use ExtractAllEntries to extract SOLID archives.
```
I found a .rar file in the S07 directory with the following properties (not sure it's related, but it is `solid`):

![image](https://user-images.githubusercontent.com/61830/40888317-565f36ea-670a-11e8-88ba-01c32a61ea2a.png)

**Comment by zerratar** [comment]
@hellfirehd Another great finding! Thank you! :)

I'm able to reproduce this error as well by faking the same videoname you provided above. I will fix this asap!

**Comment by zerratar** [comment]
I've pushed a fix for Solid rar files now. Please give it another try when you got the chance.

I will close this issue as I can't see why it shouldn't work now. But if it do, for any reason. Just open a new issue.

Thanks again, @hellfirehd !
