### ISSUE TITLE
Cannot create a file when that file already exists

### ISSUE THREAD

**Issue by hellfirehd** [zerratar/SubSync#14]
First time running with the new --resync option:
```
PS D:\SubSync> dotnet run --project .\src\SubSync\SubSync.csproj \\c3p0\storage\media -resync  -exit
...
 Synchronizing Mary Poppins (1964) [720] [tt0058331].avi
 [DBG] get-async: 'Mary Poppins (1964) [720] [tt0058331].avi'
 [DBG] OpenSubtitles login successefull
 [DBG] Searching for 'Mary Poppins (1964) [720] [tt0058331].avi'...
 [DBG] Searching with query 'Mary Poppins (1964) [720] [tt0058331].avi'...
 Synchronization of Mary Poppins (1964) [720] [tt0058331].avi failed with: Cannot create a file when that file already exists
```
They don't all fail, but a significant percentage do.

**Comment by zerratar** [comment]
I've pushed a potential fix for this issue. Please retry it when you get the chance and see if it works better for you. I was able to reproduce the error and got it working.

I will close this after you can confirm that it does in fact work for you.

**Comment by hellfirehd** [comment]
Yup, looking good now!  Nothing but the usual subscene failed after 3 retries.

**Comment by zerratar** [comment]
Great! Well, almost great! That it keeps failing on some subtitles are sad. I will close this issue and open a new one aimed for improving the continued failed downloads.

Thanks!
