### ISSUE TITLE
Configuraable Request Interval

### ISSUE THREAD

**Issue by hellfirehd** [zerratar/SubSync#2]
After a few hundred (thousand?) requests all requests start failing.  I think it is likely my IP Address has reached a limit and SubScene is now hard blocking me.  The logging doesn't indicate the reason it failed but when it goes from only the odd requests here and there failing to every request failing I think thats probably a good indicator.

If the there was a configurable delay between requests this could help mitigate outright blocking.

**Comment by zerratar** [comment]
@hellfirehd Good suggestion, I will take a look at it!

**Comment by zerratar** [comment]
I've just added a --delay <milliseconds> argument that you can use for this. Unfortunately it will make all requests sequential instead of concurrent.
