### ISSUE TITLE
-lang Is Not working

### ISSUE THREAD

**Issue by nachourpi** [zerratar/SubSync#27]
Apparently this parameter stopped working since last update as the commando :
SubSync.exe "D:\Media" -lang spanish 
Is not listing any movie file... but when I run it without the -lang parameter, it start scrapping all movie files.

**Comment by nachourpi** [comment]
The problem is that every language has to be passed with ; semicolon at the end...

**Comment by amirtal** [comment]
@nachourpi, can you please detail how you got this working?
tried every possible variant of language with or without `;`
`-lang he;heb;hebrew;english;`
`-lang hebrew;english;`
`-lang hebrew;english`

even `-lang english` just hangs...
