### ISSUE TITLE
Missing dependency in Binary release

### ISSUE THREAD

**Issue by glenneroo** [zerratar/SubSync#6]
Running the include binary or the binary from the release package causes the following error on my Win10 system:

Error:
  An assembly specified in the application dependencies manifest (SubSync.deps.json) was not found:
    package: 'SharpCompress', version: '0.20.0'
    path: 'lib/netstandard2.0/SharpCompress.dll'

**Comment by zerratar** [comment]
Thank you for reporting this issue!

I will update the release as soon as possible!
