### ISSUE TITLE
Missing binaries

### ISSUE THREAD

**Issue by mbnoimi** [zerratar/SubSync#9]
In https://github.com/zerratar/SubSync/tree/v0.1.4 release I can't see *.exe file!

**Comment by zerratar** [comment]
Did you download the binaries from the release tab?

https://github.com/zerratar/SubSync/releases

**Comment by mbnoimi** [comment]
> Did you download the binaries from the release tab?

Yep

**Comment by zerratar** [comment]
@mbnoimi Eew. The horror, thanks to .NET Core, only way to get an .exe file is to build a self-contained application that includes the whole dotnet core library...
The content is 64mb or 28.5mb compressed. When it could have been tops 300kb.. Shit.

I will add this zip for now to the release, named: **self-contained-win10-x64.zip**, and try and fix a standard version for future releases.

Thanks for pointing this out though!
